// src/views/redirect.tsx
import { useMessage } from 'naive-ui'

const Redirect = () => {
  const message = useMessage()
  const router = useRouter()
  const route = useRoute()

  router.replace({ path: `/${route.params.path}`, query: route.query }).catch((err) => {
    message.warning(err)
  })

  return <></>
}

export default Redirect

// src/views/redirect/index.tsx
import { useMessage } from 'naive-ui'
import { defineComponent } from 'vue'
import { useRoute, useRouter } from 'vue-router'

export default defineComponent({
  name: 'Redirect',
  setup() {
    const { params, query } = useRoute()
    const router = useRouter()

    router.replace({ path: `/${params.path}`, query }).catch(err => {
      useMessage().warning(err)
    })

    return () => <></>
  },
})
