// src/views/redirect.vue
<template>重定向</template>

<script lang="ts" setup>
import { useMessage } from 'naive-ui'

const message = useMessage()
const route = useRoute()
const router = useRouter()

router.replace({ path: `/${route.params.path}`, query: route.query }).catch((err) => {
  message.warning(err)
})
</script>

<style lang="scss" scoped></style>

// src/views/redirect.tsx
import { useMessage } from 'naive-ui'

const Redirect = () => {
  const message = useMessage()
  const router = useRouter()
  const route = useRoute()

  router.replace({ path: `/${route.params.path}`, query: route.query }).catch((err) => {
    message.warning(err)
  })

  return <></>
}

export default Redirect
